version: "3.3"

volumes:
  portainer_data:

services:
   portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer_data:/data
    ports:
        - 9000:9000
        - 8000:8000
        
   aria2-pro:
    container_name: aria2-pro
    image: p3terx/aria2-pro
    environment:
      - PUID=65534
      - PGID=65534
      - UMASK_SET=022
      - RPC_SECRET=aria2
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Asia/Taipei
    volumes:
      - ./aria2-config:/config
      - /public/downloads:/downloads
    ports:
      - 6800:6800
      - 6888:6888
      - 6888:6888/udp
    restart: unless-stopped
# Since Aria2 will continue to generate logs, limit the log size to 1M to prevent your hard disk from running out of space.
    logging:
      driver: json-file
      options:
        max-size: 1m
# AriaNg is just a static web page, usually you only need to deploy on a single host.
   ariang:
    container_name: ariang
    image: p3terx/ariang
    network_mode: bridge
    ports:
      - 6880:6880
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
# jdownloader 以下需手動設定
# Extraction: Subpath => true
# Extraction: Deep Extraction => false
# LinkgrabberSettings: Linkgrabber Auto Confirm => true
# LinkgrabberSettings: Auto Extraction => false
   jdownloader:
    image: jaymoulin/jdownloader
    container_name: jdownloader
    restart: unless-stopped
    ports:
        - 3129:3129
    volumes:
        - ./JDownloader-cfg:/opt/JDownloader/cfg
        - /public/jd-downloads:/opt/JDownloader/Downloads
        - /etc/localtime:/etc/localtime:ro #optional
    environment: 
        LANG: C.UTF-8
        MYJD_USER: yashichi05@gmail.com #optional (see [Identify](https://github.com/jaymoulin/docker-jdownloader#identify))
        MYJD_PASSWORD: h05h05h05 #optional (see [Identify](https://github.com/jaymoulin/docker-jdownloader#identify))
        MYJD_DEVICE_NAME: nas #optional

   samba:
    image: dperson/samba
    container_name: samba
    restart: unless-stopped
    volumes:
        - /public:/mount
    environment: 
        SHARE: public;/mount;yes;no;yes
    ports:
        - 445:445
        - 139:139
    restart: unless-stopped
